version: '3'
services:
  back:
    container_name: 'back'
    build:
      context: '.docker/'
      args:
        - USER_ID
        - GROUP_ID
    volumes:
      - './project/:/var/www/project'

  nginx:
    container_name: 'nginx'
    image: nginx
    ports:
      - "88:80"
    volumes:
      - './.docker/nginxconf:/etc/nginx/conf.d'
      - './project/:/var/www/project'

  postgres:
    container_name: 'postgres'
    image: postgres:13
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: laraveldb
    volumes:
      - postgresdb:/var/lib/postgresql/data

volumes:
  postgresdb:
    driver: local