version: '2'
services:
  apache:
    build:
      context: ./docker/
      dockerfile: ./apache.docker
    volumes:
      - ./workspace/:/var/www/
      - ./vhost/:/var/vhost/
      - ./docker/vhost-conf/:/etc/apache2/sites-enabled/
      - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    ports:
      - "80:80"
